export const categories = {
  animals: {name: 'Tiere', backgroundColor: '#ffec00', color: '#303880'},
  food: {name: 'Essen', backgroundColor: '#f0949c', color: 'white'},
  kitchen: {name: 'Küche', backgroundColor: '#ea4c73', color: 'white'},
  humans: {name: 'Menschen', backgroundColor: '#f2c6bf', color: '#303880'},
  feeelings: {name: 'Gefühle', backgroundColor: '#fce9f3', color: '#303880'},
  hobbies: {name: 'Hobbies', backgroundColor: '#63bfb3', color: 'white'},
  weather: {name: 'Wetter', backgroundColor: '#c2d458', color: 'white'},
  objects: {name: 'Gegenstände', backgroundColor: '#eb5a39', color: 'white'},
  manners: {
    name: 'Höflichkeitsformen',
    backgroundColor: '#b76eab',
    color: 'white',
  },
  nature: {name: 'Natur', backgroundColor: '#036e4b', color: 'white'},
  activites: {name: 'Aktivitäten', backgroundColor: '#303880', color: 'white'},
  hygiene: {name: 'Hygiene', backgroundColor: '#d5ecf6', color: '#303880'},
  adjectives: {name: 'Wie-Wörter', backgroundColor: '#6988bb', color: 'white'},
};

export const categoriesArray = [
  ['animals', {name: 'Tiere', backgroundColor: '#ffec00', color: '#303880'}],
  ['food', {name: 'Essen', backgroundColor: '#f0949c', color: 'white'}],
  ['kitchen', {name: 'Küche', backgroundColor: '#ea4c73', color: 'white'}],
  ['humans', {name: 'Menschen', backgroundColor: '#f2c6bf', color: '#303880'}],
  ['feeelings', {name: 'Gefühle', backgroundColor: '#fce9f3', color: '#303880'}],
  ['hobbies', {name: 'Hobbies', backgroundColor: '#63bfb3', color: 'white'}],
  ['weather', {name: 'Wetter', backgroundColor: '#c2d458', color: 'white'}],
  ['objects', {name: 'Gegenstände', backgroundColor: '#eb5a39', color: 'white'}],
  ['manners', {name: 'Höflichkeitsformen', backgroundColor: '#b76eab', color: 'white'}],
  ['nature', {name: 'Natur', backgroundColor: '#036e4b', color: 'white'}],
  ['activites', {name: 'Aktivitäten', backgroundColor: '#303880', color: 'white'}],
  ['hygiene', {name: 'Hygiene', backgroundColor: '#d5ecf6', color: '#303880'}],
  ['adjectives', {name: 'Wie-Wörter', backgroundColor: '#6988bb', color: 'white'}],
];
