export const categories = {
  animals: { name: 'Tie\u00ADre', backgroundColor: '#ffec00', color: '#303880' },
  food: { name: 'Es\u00ADsen', backgroundColor: '#f0949c', color: 'white' },
  kitchen: { name: 'Kü\u00ADche', backgroundColor: '#ea4c73', color: 'white' },
  humans: { name: 'Men\u00ADschen', backgroundColor: '#f2c6bf', color: '#303880' },
  feeelings: { name: 'Ge\u00ADfüh\u00ADle', backgroundColor: '#fce9f3', color: '#303880' },
  hobbies: { name: 'Hob\u00ADbies', backgroundColor: '#63bfb3', color: 'white' },
  weather: { name: 'Wet\u00ADter', backgroundColor: '#c2d458', color: 'white' },
  objects: { name: 'Ge\u00ADgen\u00ADstän\u00ADde', backgroundColor: '#eb5a39', color: 'white' },
  manners: {
    name: 'Höf\u00ADlich\u00ADkeits\u00ADformen',
    backgroundColor: '#b76eab',
    color: 'white',
  },
  nature: { name: 'Na\u00ADtur', backgroundColor: '#036e4b', color: 'white' },
  activites: { name: 'Ak\u00ADti\u00ADvi\u00ADtä\u00ADten', backgroundColor: '#303880', color: 'white' },
  hygiene: { name: 'Hy\u00ADgie\u00ADne', backgroundColor: '#d5ecf6', color: '#303880' },
  adjectives: { name: 'Wie-Wör\u00ADter', backgroundColor: '#6988bb', color: 'white' },
};

export const categoriesArray = [
  ['animals', { name: 'Tie\u00ADre', backgroundColor: '#ffec00', color: '#303880' }],
  ['food', { name: 'Es\u00ADsen', backgroundColor: '#f0949c', color: 'white' }],
  ['kitchen', { name: 'Kü\u00ADche', backgroundColor: '#ea4c73', color: 'white' }],
  ['humans', { name: 'Men\u00ADschen', backgroundColor: '#f2c6bf', color: '#303880' }],
  ['feeelings', { name: 'Ge\u00ADfüh\u00ADle', backgroundColor: '#fce9f3', color: '#303880' }],
  ['hobbies', { name: 'Hob\u00ADbies', backgroundColor: '#63bfb3', color: 'white' }],
  ['weather', { name: 'Wet\u00ADter', backgroundColor: '#c2d458', color: 'white' }],
  ['objects', { name: 'Ge\u00ADgen\u00ADstän\u00ADde', backgroundColor: '#eb5a39', color: 'white' }],
  ['manners', { name: 'Höf\u00ADlich\u00ADkeits\u00ADformen', backgroundColor: '#b76eab', color: 'white' }],
  ['nature', { name: 'Na\u00ADtur', backgroundColor: '#036e4b', color: 'white' }],
  ['activites', { name: 'Ak\u00ADti\u00ADvi\u00ADtä\u00ADten', backgroundColor: '#303880', color: 'white' }],
  ['hygiene', { name: 'Hy\u00ADgie\u00ADne', backgroundColor: '#d5ecf6', color: '#303880' }],
  ['adjectives', { name: 'Wie-Wör\u00ADter', backgroundColor: '#6988bb', color: 'white' }],
];
